name: Continuous Integration
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python version 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.17
          architecture: x64
      - name: Run Test
        run: python unittests.py
